spring.application.name=inventorymanager
spring.datasource.url=jdbc:postgresql://localhost:5432/inventorymanager
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
mybatis.mapper-locations=classpath:mappers/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
